# Site settings
title: Hailey Petway's Web Development Blog
email: hlpetway+blog@gmail.com
description: "This is my personal blog about my experience in Code Fellow's Full Stack JavaScript Development Accelorator and programming in general."
baseurl: "/blog"
url: ""

# Build settings
markdown: kramdown
permalink: pretty
